INSERT INTO BOOKS (NAME,LESSONNAME)  VALUES  ('data','data');
INSERT INTO BOOKS (NAME,LESSONNAME)  VALUES  ('data1','data1');
INSERT INTO BOOKS (NAME,LESSONNAME)  VALUES  ('data2','data2');
INSERT INTO BOOKS (NAME,LESSONNAME)  VALUES  ('data3','data3');
INSERT INTO BOOKS (NAME,LESSONNAME)  VALUES  ('data4','data4');